import type {
  GamificationConfig,
  Level,
  Achievement,
  Badge,
} from '../core/types';

const ecommerceLevels: Level[] = [
  { id: 'ecommerce_level_1', name: 'Shopper', xpRequired: 0 },
  { id: 'ecommerce_level_2', name: 'Regular', xpRequired: 100 },
  { id: 'ecommerce_level_3', name: 'Member', xpRequired: 300 },
  { id: 'ecommerce_level_4', name: 'VIP', xpRequired: 600 },
  { id: 'ecommerce_level_5', name: 'Gold', xpRequired: 1200 },
  { id: 'ecommerce_level_6', name: 'Platinum', xpRequired: 2500 },
  { id: 'ecommerce_level_7', name: 'Diamond', xpRequired: 5000 },
  { id: 'ecommerce_level_8', name: 'Elite', xpRequired: 10000 },
];

const ecommerceAchievements: Achievement[] = [
  {
    id: 'first_purchase',
    name: 'Welcome Shopper',
    description: 'Make your first purchase',
    icon: '🛍️',
    category: 'purchases',
    xpReward: 50,
    requirement: { type: 'count', target: 1, eventId: 'purchase_complete' },
  },
  {
    id: 'purchases_5',
    name: 'Regular Customer',
    description: 'Make 5 purchases',
    icon: '🛒',
    category: 'purchases',
    xpReward: 100,
    requirement: { type: 'count', target: 5, eventId: 'purchase_complete' },
  },
  {
    id: 'purchases_25',
    name: 'Loyal Shopper',
    description: 'Make 25 purchases',
    icon: '💝',
    category: 'purchases',
    xpReward: 300,
    requirement: { type: 'count', target: 25, eventId: 'purchase_complete' },
  },
  {
    id: 'purchases_100',
    name: 'Super Customer',
    description: 'Make 100 purchases',
    icon: '👑',
    category: 'purchases',
    xpReward: 1000,
    requirement: { type: 'count', target: 100, eventId: 'purchase_complete' },
  },

  {
    id: 'first_review',
    name: 'Voice of Customer',
    description: 'Write your first review',
    icon: '✍️',
    category: 'reviews',
    xpReward: 25,
    requirement: { type: 'count', target: 1, eventId: 'review_posted' },
  },
  {
    id: 'reviews_10',
    name: 'Reviewer',
    description: 'Write 10 reviews',
    icon: '⭐',
    category: 'reviews',
    xpReward: 100,
    requirement: { type: 'count', target: 10, eventId: 'review_posted' },
  },
  {
    id: 'reviews_50',
    name: 'Top Reviewer',
    description: 'Write 50 reviews',
    icon: '🌟',
    category: 'reviews',
    xpReward: 300,
    requirement: { type: 'count', target: 50, eventId: 'review_posted' },
  },
  {
    id: 'helpful_review',
    name: 'Helpful Voice',
    description: 'Get 10 helpful votes on a review',
    icon: '👍',
    category: 'reviews',
    xpReward: 50,
    requirement: { type: 'count', target: 1, eventId: 'review_helpful' },
  },

  {
    id: 'wishlist_10',
    name: 'Dream Collector',
    description: 'Add 10 items to wishlist',
    icon: '💫',
    category: 'wishlist',
    xpReward: 50,
    requirement: { type: 'count', target: 10, eventId: 'wishlist_add' },
  },
  {
    id: 'wishlist_purchase',
    name: 'Dream Come True',
    description: 'Purchase 5 items from your wishlist',
    icon: '🎁',
    category: 'wishlist',
    xpReward: 150,
    requirement: { type: 'count', target: 5, eventId: 'wishlist_purchase' },
  },

  {
    id: 'daily_visit_7',
    name: 'Weekly Visitor',
    description: 'Visit the store 7 days in a row',
    icon: '📅',
    category: 'engagement',
    xpReward: 100,
    requirement: { type: 'streak', target: 7, eventId: 'daily_visit' },
  },
  {
    id: 'daily_visit_30',
    name: 'Monthly Regular',
    description: 'Visit the store 30 days in a row',
    icon: '🗓️',
    category: 'engagement',
    xpReward: 400,
    requirement: { type: 'streak', target: 30, eventId: 'daily_visit' },
  },

  {
    id: 'spend_100',
    name: 'Big Spender',
    description: 'Spend $100 total',
    icon: '💵',
    category: 'spending',
    xpReward: 100,
    requirement: { type: 'total', target: 100, eventId: 'dollars_spent' },
    isSecret: true,
  },
  {
    id: 'spend_500',
    name: 'VIP Spender',
    description: 'Spend $500 total',
    icon: '💎',
    category: 'spending',
    xpReward: 300,
    requirement: { type: 'total', target: 500, eventId: 'dollars_spent' },
    isSecret: true,
  },
  {
    id: 'spend_1000',
    name: 'Premium Member',
    description: 'Spend $1,000 total',
    icon: '👑',
    category: 'spending',
    xpReward: 600,
    requirement: { type: 'total', target: 1000, eventId: 'dollars_spent' },
    isSecret: true,
  },
];

const ecommerceBadges: Badge[] = [
  {
    id: 'early_adopter',
    name: 'Early Adopter',
    description: 'Joined during the first month',
    icon: '🚀',
    rarity: 'legendary',
  },
  {
    id: 'verified_reviewer',
    name: 'Verified Reviewer',
    description: 'Verified purchase reviewer',
    icon: '✅',
    rarity: 'rare',
  },
  {
    id: 'trendsetter',
    name: 'Trendsetter',
    description: 'Purchased trending items',
    icon: '🔥',
    rarity: 'epic',
  },
];

export const ecommercePreset: GamificationConfig = {
  levels: ecommerceLevels,
  achievements: ecommerceAchievements,
  badges: ecommerceBadges,
  xpMultiplier: 1,
  persistenceKey: 'gamify_ecommerce_data',
};
