import type {
  GamificationConfig,
  Level,
  Achievement,
  Badge,
} from '../core/types';

const fitnessLevels: Level[] = [
  { id: 'fitness_level_1', name: 'Couch Potato', xpRequired: 0 },
  { id: 'fitness_level_2', name: 'Beginner', xpRequired: 100 },
  { id: 'fitness_level_3', name: 'Active', xpRequired: 300 },
  { id: 'fitness_level_4', name: 'Fit', xpRequired: 600 },
  { id: 'fitness_level_5', name: 'Athlete', xpRequired: 1000 },
  { id: 'fitness_level_6', name: 'Champion', xpRequired: 1500 },
  { id: 'fitness_level_7', name: 'Elite', xpRequired: 2500 },
  { id: 'fitness_level_8', name: 'Legend', xpRequired: 4000 },
];

const fitnessAchievements: Achievement[] = [
  {
    id: 'first_workout',
    name: 'First Steps',
    description: 'Complete your first workout',
    icon: '👟',
    category: 'workouts',
    xpReward: 50,
    requirement: { type: 'count', target: 1, eventId: 'workout_complete' },
  },
  {
    id: 'workout_10',
    name: 'Getting into It',
    description: 'Complete 10 workouts',
    icon: '💪',
    category: 'workouts',
    xpReward: 100,
    requirement: { type: 'count', target: 10, eventId: 'workout_complete' },
  },
  {
    id: 'workout_50',
    name: 'Dedicated',
    description: 'Complete 50 workouts',
    icon: '🏋️',
    category: 'workouts',
    xpReward: 300,
    requirement: { type: 'count', target: 50, eventId: 'workout_complete' },
  },
  {
    id: 'workout_100',
    name: 'Century Club',
    description: 'Complete 100 workouts',
    icon: '🏆',
    category: 'workouts',
    xpReward: 500,
    requirement: { type: 'count', target: 100, eventId: 'workout_complete' },
  },
  {
    id: 'streak_3',
    name: 'On a Roll',
    description: 'Maintain a 3-day streak',
    icon: '🔥',
    category: 'streaks',
    xpReward: 50,
    requirement: { type: 'streak', target: 3, eventId: 'daily_checkin' },
  },
  {
    id: 'streak_7',
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: '⭐',
    category: 'streaks',
    xpReward: 150,
    requirement: { type: 'streak', target: 7, eventId: 'daily_checkin' },
  },
  {
    id: 'streak_30',
    name: 'Monthly Master',
    description: 'Maintain a 30-day streak',
    icon: '👑',
    category: 'streaks',
    xpReward: 500,
    requirement: { type: 'streak', target: 30, eventId: 'daily_checkin' },
  },
  {
    id: 'walk_10km',
    name: 'Walker',
    description: 'Walk 10km total',
    icon: '🚶',
    category: 'distance',
    xpReward: 75,
    requirement: { type: 'total', target: 10, eventId: 'km_walked' },
  },
  {
    id: 'run_50km',
    name: 'Runner',
    description: 'Run 50km total',
    icon: '🏃',
    category: 'distance',
    xpReward: 200,
    requirement: { type: 'total', target: 50, eventId: 'km_run' },
  },
  {
    id: 'cycle_100km',
    name: 'Cyclist',
    description: 'Cycle 100km total',
    icon: '🚴',
    category: 'distance',
    xpReward: 300,
    requirement: { type: 'total', target: 100, eventId: 'km_cycled' },
  },
  {
    id: 'calories_1000',
    name: 'Calorie Burner',
    description: 'Burn 1,000 calories',
    icon: '🔥',
    category: 'calories',
    xpReward: 100,
    requirement: { type: 'total', target: 1000, eventId: 'calories_burned' },
  },
  {
    id: 'calories_10000',
    name: 'Inferno',
    description: 'Burn 10,000 calories',
    icon: '💥',
    category: 'calories',
    xpReward: 500,
    requirement: { type: 'total', target: 10000, eventId: 'calories_burned' },
  },
];

const fitnessBadges: Badge[] = [
  {
    id: 'gym_rat',
    name: 'Gym Rat',
    description: 'Completed 10 gym sessions',
    icon: '🏋️',
    rarity: 'common',
  },
  {
    id: 'early_bird',
    name: 'Early Bird',
    description: 'Completed a morning workout',
    icon: '🌅',
    rarity: 'common',
  },
  {
    id: 'hydrated',
    name: 'Hydrated',
    description: 'Logged water intake for 7 days',
    icon: '💧',
    rarity: 'common',
  },
  {
    id: 'marathon_ready',
    name: 'Marathon Ready',
    description: 'Ran 42km total',
    icon: '🏃',
    rarity: 'rare',
  },
  {
    id: 'iron_will',
    name: 'Iron Will',
    description: 'Maintained a 14-day streak',
    icon: '🔗',
    rarity: 'rare',
  },
  {
    id: 'cardio_king',
    name: 'Cardio King',
    description: 'Burned 5,000 calories',
    icon: '❤️',
    rarity: 'rare',
  },
  {
    id: 'beast_mode',
    name: 'Beast Mode',
    description: 'Completed 100 workouts',
    icon: '🦍',
    rarity: 'epic',
  },
  {
    id: 'ironman',
    name: 'Ironman',
    description: 'Swam, cycled, and ran in one week',
    icon: '🦸',
    rarity: 'epic',
  },
  {
    id: 'fitness_legend',
    name: 'Fitness Legend',
    description: 'Reached the Legend level',
    icon: '🏆',
    rarity: 'legendary',
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'Maintained a 100-day streak',
    icon: '⚡',
    rarity: 'legendary',
  },
];

export const fitnessPreset: GamificationConfig = {
  levels: fitnessLevels,
  achievements: fitnessAchievements,
  badges: fitnessBadges,
  xpMultiplier: 1,
  persistenceKey: 'gamify_fitness_data',
};
