import type {
  GamificationConfig,
  Level,
  Achievement,
  Badge,
} from '../core/types';

const learningLevels: Level[] = [
  { id: 'learning_level_1', name: 'Novice', xpRequired: 0 },
  { id: 'learning_level_2', name: 'Student', xpRequired: 100 },
  { id: 'learning_level_3', name: 'Learner', xpRequired: 250 },
  { id: 'learning_level_4', name: 'Scholar', xpRequired: 500 },
  { id: 'learning_level_5', name: 'Expert', xpRequired: 1000 },
  { id: 'learning_level_6', name: 'Master', xpRequired: 2000 },
  { id: 'learning_level_7', name: 'Guru', xpRequired: 3500 },
  { id: 'learning_level_8', name: 'Sage', xpRequired: 5500 },
  { id: 'learning_level_9', name: 'Visionary', xpRequired: 8000 },
  { id: 'learning_level_10', name: 'Enlightened', xpRequired: 12000 },
];

const learningAchievements: Achievement[] = [
  {
    id: 'first_lesson',
    name: 'First Step',
    description: 'Complete your first lesson',
    icon: '📖',
    category: 'progress',
    xpReward: 25,
    requirement: {
      type: 'count',
      target: 1,
      eventId: 'lesson_complete',
    },
  },
  {
    id: 'lessons_10',
    name: 'Getting Started',
    description: 'Complete 10 lessons',
    icon: '📚',
    category: 'progress',
    xpReward: 75,
    requirement: {
      type: 'count',
      target: 10,
      eventId: 'lesson_complete',
    },
  },
  {
    id: 'lessons_50',
    name: 'Half Century',
    description: 'Complete 50 lessons',
    icon: '🎓',
    category: 'progress',
    xpReward: 200,
    requirement: { type: 'count', target: 50, eventId: 'lesson_complete' },
  },
  {
    id: 'lessons_100',
    name: 'Century Scholar',
    description: 'Complete 100 lessons',
    icon: '🏆',
    category: 'progress',
    xpReward: 400,
    requirement: { type: 'count', target: 100, eventId: 'lesson_complete' },
  },
  {
    id: 'course_complete_1',
    name: 'Course Graduate',
    description: 'Complete your first course',
    icon: '📜',
    category: 'courses',
    xpReward: 100,
    requirement: { type: 'count', target: 1, eventId: 'course_complete' },
  },
  {
    id: 'course_complete_5',
    name: 'Multi-Disciplinary',
    description: 'Complete 5 courses',
    icon: '🎯',
    category: 'courses',
    xpReward: 300,
    requirement: { type: 'count', target: 5, eventId: 'course_complete' },
  },
  {
    id: 'course_complete_10',
    name: 'Knowledge Seeker',
    description: 'Complete 10 courses',
    icon: '🌟',
    category: 'courses',
    xpReward: 600,
    requirement: { type: 'count', target: 10, eventId: 'course_complete' },
  },
  {
    id: 'study_streak_3',
    name: 'Consistent',
    description: 'Study for 3 days in a row',
    icon: '📅',
    category: 'streaks',
    xpReward: 50,
    requirement: { type: 'streak', target: 3, eventId: 'daily_study' },
  },
  {
    id: 'study_streak_7',
    name: 'Week Learner',
    description: 'Study for 7 days in a row',
    icon: '🗓️',
    category: 'streaks',
    xpReward: 150,
    requirement: { type: 'streak', target: 7, eventId: 'daily_study' },
  },
  {
    id: 'study_streak_30',
    name: 'Monthly Master',
    description: 'Study for 30 days in a row',
    icon: '🏅',
    category: 'streaks',
    xpReward: 500,
    requirement: { type: 'streak', target: 30, eventId: 'daily_study' },
  },
  {
    id: 'quiz_perfect',
    name: 'Perfect Score',
    description: 'Get 100% on a quiz',
    icon: '💯',
    category: 'quizzes',
    xpReward: 75,
    requirement: { type: 'count', target: 1, eventId: 'quiz_perfect' },
  },
  {
    id: 'quiz_perfect_10',
    name: 'Quiz Master',
    description: 'Get 100% on 10 quizzes',
    icon: '🧠',
    category: 'quizzes',
    xpReward: 250,
    requirement: { type: 'count', target: 10, eventId: 'quiz_perfect' },
  },
  {
    id: 'study_time_1h',
    name: 'Focused Hour',
    description: 'Study for 1 hour total',
    icon: '⏰',
    category: 'time',
    xpReward: 50,
    requirement: { type: 'total', target: 60, eventId: 'minutes_studied' },
  },
  {
    id: 'study_time_10h',
    name: 'Dedicated Learner',
    description: 'Study for 10 hours total',
    icon: '⌛',
    category: 'time',
    xpReward: 200,
    requirement: { type: 'total', target: 600, eventId: 'minutes_studied' },
  },
  {
    id: 'study_time_100h',
    name: 'Knowledge Sage',
    description: 'Study for 100 hours total',
    icon: '⏳',
    category: 'time',
    xpReward: 1000,
    requirement: { type: 'total', target: 6000, eventId: 'minutes_studied' },
  },
];

const learningBadges: Badge[] = [
  {
    id: 'bookworm',
    name: 'Bookworm',
    description: 'Completed 10 lessons',
    icon: '📚',
    rarity: 'common',
  },
  {
    id: 'note_taker',
    name: 'Note Taker',
    description: 'Saved 50 notes',
    icon: '📝',
    rarity: 'common',
  },
  {
    id: 'curious_mind',
    name: 'Curious Mind',
    description: 'Explored 5 different subjects',
    icon: '🔍',
    rarity: 'common',
  },
  {
    id: 'punctual',
    name: 'Punctual',
    description: 'Studied at the same time for 7 days',
    icon: '⏰',
    rarity: 'common',
  },
  {
    id: 'quick_learner',
    name: 'Quick Learner',
    description: 'Completed a course in record time',
    icon: '⚡',
    rarity: 'rare',
  },
  {
    id: 'quiz_whiz',
    name: 'Quiz Whiz',
    description: 'Got 100% on 5 quizzes',
    icon: '🎯',
    rarity: 'rare',
  },
  {
    id: 'polyglot',
    name: 'Polyglot',
    description: 'Studied 3 different languages',
    icon: '🌍',
    rarity: 'rare',
  },
  {
    id: 'scholar',
    name: 'Scholar',
    description: 'Completed 50 courses',
    icon: '🎓',
    rarity: 'epic',
  },
  {
    id: 'perfectionist',
    name: 'Perfectionist',
    description: 'Got 100% on 25 quizzes',
    icon: '💎',
    rarity: 'epic',
  },
  {
    id: 'knowledge_master',
    name: 'Knowledge Master',
    description: 'Mastered 10 subjects',
    icon: '🧠',
    rarity: 'epic',
  },
  {
    id: 'enlightened',
    name: 'Enlightened',
    description: 'Reached the highest level',
    icon: '🌟',
    rarity: 'legendary',
  },
  {
    id: 'wisdom_seeker',
    name: 'Wisdom Seeker',
    description: 'Studied for 1000 hours total',
    icon: '👁️',
    rarity: 'legendary',
  },
];

export const learningPreset: GamificationConfig = {
  levels: learningLevels,
  achievements: learningAchievements,
  badges: learningBadges,
  xpMultiplier: 1,
  persistenceKey: 'gamify_learning_data',
};
